# Generated by Django 3.2.25 on 2025-11-18 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('sender', 'Sender'), ('carrier', 'Carrier')], default='sender', max_length=10),
        ),
    ]
